# Generated by Django 5.1.15 on 2026-03-20 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("domain", models.CharField(blank=True, max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("gadgets", "Gadgets"),
                            ("accessories", "Accessories"),
                            ("grooming", "Grooming"),
                            ("fashion", "Fashion"),
                            ("home", "Home"),
                        ],
                        max_length=20,
                    ),
                ),
                ("logo_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("image_url", models.URLField(blank=True)),
                ("source_url", models.URLField(blank=True)),
                ("main_claims", models.TextField(blank=True)),
                ("specs", models.JSONField(blank=True, default=dict)),
                ("variants", models.JSONField(blank=True, default=list)),
                ("last_crawled", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="catalog.brand",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Comparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("pros_a", models.TextField(blank=True)),
                ("cons_a", models.TextField(blank=True)),
                ("pros_b", models.TextField(blank=True)),
                ("cons_b", models.TextField(blank=True)),
                (
                    "winner_for",
                    models.TextField(
                        blank=True,
                        help_text="Description of who each product is best for",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons_as_a",
                        to="catalog.product",
                    ),
                ),
                (
                    "product_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons_as_b",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrendEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("why_trending", models.TextField()),
                (
                    "creator_hooks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of string angles for creators",
                    ),
                ),
                (
                    "platform_fit",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Platforms this product fits, e.g. ["tiktok","youtube"]',
                    ),
                ),
                (
                    "trend_score",
                    models.IntegerField(
                        help_text="1-10 score indicating trend strength"
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trend_entry",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "trend entries",
                "ordering": ["-trend_score", "-added_at"],
            },
        ),
        migrations.CreateModel(
            name="UseCasePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("audience", models.CharField(max_length=255)),
                ("budget_max", models.IntegerField(help_text="Maximum budget in USD")),
                ("cautions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "top_picks",
                    models.ManyToManyField(
                        blank=True, related_name="use_case_pages", to="catalog.product"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
