# Generated by Django 5.1.15 on 2026-03-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_productchangelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="comparison",
            name="meta_description",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="comparison",
            name="meta_title",
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name="comparison",
            name="og_image",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_description",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_title",
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name="product",
            name="og_image",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="usecasepage",
            name="meta_description",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="usecasepage",
            name="meta_title",
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name="usecasepage",
            name="og_image",
            field=models.URLField(blank=True),
        ),
    ]
