# Generated by Django 5.1.15 on 2026-03-20 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_comparison_meta_description_comparison_meta_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("source_page", models.CharField(blank=True, max_length=255)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-subscribed_at"],
            },
        ),
        migrations.CreateModel(
            name="AffiliateLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "network_name",
                    models.CharField(
                        help_text='e.g. "Amazon Associates", "ShareASale"',
                        max_length=120,
                    ),
                ),
                ("affiliate_url", models.URLField()),
                ("click_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliate_links",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClickLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referrer", models.URLField(blank=True)),
                ("clicked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "affiliate_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="click_logs",
                        to="catalog.affiliatelink",
                    ),
                ),
            ],
            options={
                "ordering": ["-clicked_at"],
            },
        ),
    ]
