# Generated by Django 5.1.15 on 2026-05-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_emailsubscriber_affiliatelink_clicklog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comparison",
            name="og_image",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="product",
            name="og_image",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="product",
            name="source_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="usecasepage",
            name="og_image",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
